### ISSUE TITLE
Lack of URLs encoding in logo path

### ISSUE THREAD

**Issue by Qrzysio** [airly-eu/api-docs#1]
Some sensors have a sponsor and the API returns its logo. However, the path is not encoded.

The installation no. 616 (`https://airapi.airly.eu/v2/installations/616`) returns the following path:

`https://cdn.airly.eu/logo/https://cdn.airly.eu/logo/Stowarzyszenie Pracownia na rzecz Wszystkich Istot .jpg`.

Another example is the installation ID 3391. The sponsor's logo image contains polish accents. Quite a bad idea.

`https://cdn.airly.eu/logo/Ostrołęka.jpg`

Spaces are not encoded. Would be better to change image names to more readable or encode with urlecode function.

**Comment by DCzajkowski** [comment]
Thank you for reporting. We have added this to our roadmap and it should be implemented any time this week.

Have a nice day :)

**Comment by maraswrona** [comment]
@Qrzysio: This is fixed now. We have changed all our logo urls to include only English alphabet or digits, so this problem should no longer occur. Encoding urls is not needed anymore.

Thanks for reporting this issue and for using our API!
