### ISSUE TITLE
Typo in summary.md

### ISSUE THREAD

**Issue by krzdabrowski** [airly-eu/api-docs#2]
First of all, thanks for great API docs - very clear and informative, I will use it in my project for sure.

But please fix this typo in `przejżysty` - it just hurts... :)

Keep up the good work!

**Comment by DCzajkowski** [comment]
Thank you for your kind words and for reporting. Fixed in https://github.com/airly-eu/api-docs/commit/aa122da71fc87930eab06370c7686b0238bb6b02
