### ISSUE TITLE
List of possible colors returned by API

### ISSUE THREAD

**Issue by oczki** [airly-eu/api-docs#4]
As I see in the app, there's no color interpolation being made for intermediate values, meaning there must be a list of hard-coded values for each pollution level.

It would be great to have such a list of possible colors that API returns, so that it's easier to design an interface around that.

Preferably, the list would match the color against the level, e.g.:

| Level  | Color |
| ------------- | ------------- |
| VERY_LOW | #6BC926 |
| MEDIUM  | #EFBB0F  |

**Comment by BFHDD** [comment]
There is an end-point that returns definitions of all indexes [docs](https://developer.airly.eu/docs#endpoints.meta.indexes).

**Comment by oczki** [comment]
That's what I get for not reading it thoroughly... I'm closing the issue. Thank you!
