### ISSUE TITLE
Pomiary ograniczone do wartości aktualnych

### ISSUE THREAD

**Issue by Cheburashek** [airly-eu/api-docs#5]
Witam,

tworzę hobbistycznie projekt oparty na mikrokontrolerze, który m.in. ściąga dane o jakości powietrza. 
Pomimo nienajgorszych zasobów odbieranie całej paczki, buforowanie i parsowanie Json'a jest niewygodne i wymaga różnych dodatkowych zabiegów.

Zwracam się ze sugestią dodania metody pobierającej dane bez elementów "history" oraz 
"forecast".

Pozdrawiam!

**Comment by maraswrona** [comment]
@Cheburashek Dzięki za wiadomość!

Mieliśmy już podobne sugestie i sami dostrzegamy wady o ograniczenia obecnego API. Będziemy w najbliższym czasie pracować nad usprawnieniami w tym obszarze. Będziemy informować gdy pojawi się coś nowego. Stay tuned!

**Comment by DCzajkowski** [comment]
Hej @Cheburashek, dzięki za zgłoszenie. Zamknę ten issue, bo nie odnosi się bezpośrednio do dokumentacji, a pomysł zapisaliśmy w wewnętrznym backlogu. 🙃
