### ISSUE TITLE
API key is not correct.

### ISSUE THREAD

**Issue by Raportaru** [airly-eu/api-docs#6]
Thanks for this soft, is very useful, but yesterday after update home assistant i received an error (API rate limit was exceeded), i uninstal the plug in, and then add it again but i have this error: API key is not correct. after i introduce api key. Please help me, i'm new on home assistant.

**Comment by maraswrona** [comment]
Hi @Raportaru . As I said in our email conversation, we do not maintain the Home Assistant integration with Airly API. It is a third party solution, probably some open source built by the community. 

The error you received indicates that the daily quota of requests was exceeded. Please consult our documentation https://developer.airly.eu/docs#general.limits

When implementing integration with our API (whether that's some script, or some application or plugin) you should consider some strategy to stay within the limits.
